/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricity.billing.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class InterestOnDeposit extends javax.swing.JFrame {

    /**
     * Creates new form InterestOnDeposit
     */
    public InterestOnDeposit() {
        initComponents();
        setTitle("Interest On Deposit");
        
        
        try {
        	Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con4=DriverManager.getConnection("jdbc:mysql://localhost:3306/sys","root","Ckj123@0909");
            Statement st4=con4.createStatement();
            String s4="SELECT CONSUMERNO FROM CONSUMER11";
            
            ResultSet rs4=st4.executeQuery(s4);
            while(rs4.next()!=false)
            {
                String str4=rs4.getString("CONSUMERNO");
                System.out.println(str4);
                consumer_number.addItem(str4);
               
            }
            con4.close();
            st4.close();
            
        } catch (Exception ex) {
            Logger.getLogger(DataEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        area_code = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        meter_reader_code = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        consumer_number = new javax.swing.JComboBox();
        deposit_amount = new javax.swing.JTextField();
        interest = new javax.swing.JTextField();
        Allow_Interest = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("INTEREST ON DEPOSIT");

        jLabel2.setText("Area Code");

        area_code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel3.setText("Meter Reader Code");

        meter_reader_code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel4.setText("Consumer Number");

        jLabel5.setText("Deposit Amount");

        jLabel6.setText("Interest");

        consumer_number.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        consumer_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                consumer_numberFocusLost(evt);
            }
        });

        Allow_Interest.setText("Allow Interest");
        Allow_Interest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Allow_InterestActionPerformed(evt);
            }
        });

        Edit.setText("Edit & Allow");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jLabel7.setText(" (   in Percentage %  )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Allow_Interest)
                        .addGap(72, 72, 72)
                        .addComponent(Edit)
                        .addGap(75, 75, 75)
                        .addComponent(Cancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(consumer_number, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(179, 179, 179)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(area_code, 0, 125, Short.MAX_VALUE)
                                    .addComponent(meter_reader_code, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deposit_amount)
                                    .addComponent(interest))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumer_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meter_reader_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(area_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deposit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Allow_Interest)
                    .addComponent(Edit)
                    .addComponent(Cancel))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consumer_numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_consumer_numberFocusLost

        
         try {
        	 Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con4=DriverManager.getConnection("jdbc:mysql://localhost:3306/sys","root","Ckj123@0909");
             Statement st4=con4.createStatement();
            String s4="SELECT MRCODE,AREACODE FROM CONSUMER11 WHERE CONSUMERNO='"+consumer_number.getSelectedItem()+"'  ";
            
            ResultSet rs4=st4.executeQuery(s4);
            while(rs4.next()!=false)
            {
                
                meter_reader_code.addItem(rs4.getString("MRCODE"));
                area_code.addItem(rs4.getString("AREACODE"));
               
            }
            con4.close();
            st4.close();
            
        } catch (Exception ex) {
            Logger.getLogger(DataEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consumer_numberFocusLost

    private void Allow_InterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Allow_InterestActionPerformed

          if(consumer_number.getSelectedItem().equals("select")|| area_code.getSelectedItem().equals("select")  
                || meter_reader_code.getSelectedItem().equals("select")|| deposit_amount.getText().equals("") 
                || interest.getText().equals("") )
                
        {
            JOptionPane.showMessageDialog(null," Enter Correct Data In Appropriare Field");
        }
        else
        {
            try {
            String ConsumerNo1=(String)consumer_number.getSelectedItem();
            String CashDeposits=(String)area_code.getSelectedItem();
            String Acd=(String)meter_reader_code.getSelectedItem();
            double damt=Double.parseDouble(deposit_amount.getText());
            double intr=Double.parseDouble(interest.getText());
            
            double ida=damt+((damt*intr)/100);
            
            String ida01=Double.toString(ida);
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con7=DriverManager.getConnection("jdbc:mysql://localhost:3306/sys","root","Ckj123@0909");
            
            Statement st7=con7.createStatement();
            String s7="INSERT INTO INTEREST_ON_DEPOSIT_01 VALUES ('"+ConsumerNo1+"','"+CashDeposits+"', '"+Acd+"', '"+deposit_amount.getText()+"', '"+interest.getText()+"', '"+ida01+"')   ";
            
            int i7=st7.executeUpdate(s7);
            if(i7>=1)
                JOptionPane.showMessageDialog(null,"Interest Allowed.."+"\n"+ "Total Deposit Amount : "+ida);
            else
                JOptionPane.showMessageDialog(null,"Interest Not Allowed..");
            
           consumer_number.setSelectedIndex(-1);
            area_code.setSelectedIndex(-1);
            meter_reader_code.setSelectedIndex(-1);
            deposit_amount.setText("");
            interest.setText("");
            
            
            
            st7.close();
            con7.close();
            
        }
           catch (Exception ex) {
            Logger.getLogger(DataEntry.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Enter Valid Data");
        }
       }
    }//GEN-LAST:event_Allow_InterestActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed

        if(consumer_number.getSelectedItem().equals("select")|| area_code.getSelectedItem().equals("select")  
                || meter_reader_code.getSelectedItem().equals("select")|| deposit_amount.getText().equals("") 
                || interest.getText().equals("") )
                
        {
            JOptionPane.showMessageDialog(null," Enter Correct Data In Appropriare Field");
        }
        else
        {
            try {
            String ConsumerNo1=(String)consumer_number.getSelectedItem();
            String CashDeposits=(String)area_code.getSelectedItem();
            String Acd=(String)meter_reader_code.getSelectedItem();
            double damt=Double.parseDouble(deposit_amount.getText());
            double intr=Double.parseDouble(interest.getText());
            
            double ida=damt+((damt*intr)/100);
            
            String ida01=Double.toString(ida);
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con7=DriverManager.getConnection("jdbc:mysql://localhost:3306/sys","root","Ckj123@0909");
            
            Statement st7=con7.createStatement();
            String s7="UPDATE INTEREST_ON_DEPOSIT_01 SET DEPOSITAMOUNT='"+deposit_amount.getText()+"', INTEREST='"+interest.getText()+"', INTERESTED_DEPOSIT_AMOUNT='"+ida01+"'  ";
            
            int i7=st7.executeUpdate(s7);
            if(i7>=1)
                JOptionPane.showMessageDialog(null,"Awsome, Interest Allowed.."+"\n"+ "Total Deposit Amount : "+ida);
            else
                JOptionPane.showMessageDialog(null,"Interest Not Allowed..");
            
           consumer_number.setSelectedIndex(-1);
            area_code.setSelectedIndex(-1);
            meter_reader_code.setSelectedIndex(-1);
            deposit_amount.setText("");
            interest.setText("");
            
            
            
            st7.close();
            con7.close();
            
        }
           catch (Exception ex) {
            Logger.getLogger(DataEntry.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Enter Valid Data");
        }
       }
    }//GEN-LAST:event_EditActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed

        OfficeAdministration o=new OfficeAdministration();
        o.show();dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterestOnDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterestOnDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterestOnDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterestOnDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterestOnDeposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Allow_Interest;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Edit;
    private javax.swing.JComboBox area_code;
    private javax.swing.JComboBox consumer_number;
    private javax.swing.JTextField deposit_amount;
    private javax.swing.JTextField interest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox meter_reader_code;
    // End of variables declaration//GEN-END:variables
}
